[package]
name = "test_use_after_move"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29.0"
array-macro = "2.1.0"
bevy = "0.5.0"
